# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
parameters:
- name: Param1
  displayName: Parameter1
  type: string

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: './test_ps_script.ps1'
    arguments: > # Use this to avoid newline characters in multiline string
      -input1 ${{ parameters.Param1 }}
  displayName: 'Demo PS script'

- task: PowerShell@2
  displayName: 'Inline PS script'
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      Write-Host "Hello World from $Env:AGENT_NAME."
      Write-Host "My ID is $Env:AGENT_ID."
      Write-Host "AGENT_WORKFOLDER contents:"
      gci $Env:AGENT_WORKFOLDER
      Write-Host "AGENT_BUILDDIRECTORY contents:"
      gci $Env:AGENT_BUILDDIRECTORY
      Write-Host "BUILD_SOURCESDIRECTORY contents:"
      gci $Env:BUILD_SOURCESDIRECTORY
      Write-Host "Over and out."